### PR TITLE
CIEMSS 18-month Epi Scenario 1

### PR DESCRIPTION
**Pull request by djinnome**

### CODE REVIEW

**Comment by VigneshSella** [comment]
W.I.P

**Comment by VigneshSella** [comment]
@djinnome We could probably merge this into main if you'd like. Scenario 1 is as complete as it can be given the prompt and lack of model availability (which is unlikely to change over the next day).

**Comment by djinnome** [comment]
Can you elaborate on the lack of model availability issue?

**Comment by VigneshSella** [comment]
> Can you elaborate on the lack of model availability issue?

As far as I'm aware: (a) there is no appropriate model available for scenario 1 which can handle the stratification. And (b) the question might be ill-posed as it requires information on prob_hospitalization, which is only available for SEIRHD models - but we're asked to fit/calibrate a SEIRD model. 

As was discussed in the hotwash on Tuesday we to let this go and optimize for beta/gamma instead, but we would still need (a).

**Pull request merged**
